image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "32"
  ANDROID_BUILD_TOOLS: "32.1.0-rc1"
  ANDROID_SDK_TOOLS: "6514223"

# Packages installation before running script
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - export ANDROID_HOME="${PWD}/android-home"
  - install -d $ANDROID_HOME
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - pushd $ANDROID_HOME
  - unzip -d cmdline-tools cmdline-tools.zip
  - popd
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/
  - sdkmanager --version

  # use yes to accept all licenses
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true
  - sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools"
  - sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}"

  # Not necessary, but just for surity
  - chmod +x ./gradlew

# Basic android and gradle stuff
# Check linting
lintDebug:
  tags:
  -  hva
  interruptible: true
  stage: build
  rules:
    - if: $CI_COMMIT_TAG    
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

# Make Project
release_job:
  tags:
  -  hva
  interruptible: true
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG               
  script:
    - ./gradlew assembleDebug
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli' 
    tag_name: '$CI_COMMIT_TAG'                                      
    ref: '$CI_COMMIT_TAG'
    assets:
        links:
          - name: 'WearOS APK'
            filepath: app/build/**/outputs/**/*.apk
